/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Add custom colors used in components
        "blue-primary": "var(--blue-primary)",
        "blue-light": "var(--blue-light)",
        "blue-dark": "var(--blue-dark)",
        "blue-accent": "var(--blue-accent)",
        "orange-50": "#fff7ed",
        "orange-100": "#ffedd5",
        "orange-200": "#fed7aa",
        "orange-300": "#fdba74",
        "orange-400": "#fb923c",
        "orange-500": "#f97316",
        "orange-600": "#ea580c",
        "orange-700": "#c2410c",
        "orange-800": "#9a3412",
        "orange-900": "#7c2d12",
        "red-50": "#fef2f2",
        "red-100": "#fee2e2",
        "red-200": "#fecaca",
        "red-300": "#fca5a5",
        "red-400": "#f87171",
        "red-500": "#ef4444",
        "red-600": "#dc2626",
        "red-700": "#b91c1c",
        "red-800": "#991b1b",
        "red-900": "#7f1d1d",
        "gray-50": "#f9fafb",
        "gray-100": "#f3f4f6",
        "gray-200": "#e5e7eb",
        "gray-300": "#d1d5db",
        "gray-400": "#9ca3af",
        "gray-500": "#6b7280",
        "gray-600": "#4b5563",
        "gray-700": "#374151",
        "gray-800": "#1f2937",
        "gray-900": "#111827",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}
